/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package order;
import modul.koneksi;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nurhuda ganteng
 */
public class list_order extends javax.swing.JInternalFrame {

    /**
     * Creates new form list_order
     */
    public list_order() {
        initComponents();
        tampad.addColumn("Kode Order");
        tampad.addColumn("No Meja");
        tampad.addColumn("Total Order");
        tampad.addColumn("Pembayaran");
        tampad.addColumn("Kembalian");
        data_order.setModel(tampad);
        this.tampil_menu();
    }
    private DefaultTableModel tampad = new DefaultTableModel();
    
    public void hapusTabel(DefaultTableModel contoh){
        int a = contoh.getRowCount();
        for(int i = 0; i < a; i++){
            contoh.removeRow(0);
        }
    }
     
    public void tampil_menu(){
         Connection konsi = null;
        koneksi db = new koneksi();
        String sql ="";
        try{
            hapusTabel(tampad);
            konsi =db.getKoneksi();
            sql ="select kode_order,no_meja,tagihan,pembayaran,kembalian from orders";
            Statement stmt = konsi.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                String kode_order = rs.getString(1);
                String no_meja = rs.getString(2);
                String tagihan = rs.getString(3);
                String pembayaran = rs.getString(4);
                String kembalian = rs.getString(5);
                
                Object[] data ={kode_order,no_meja,tagihan,pembayaran,kembalian};
                
                tampad.addRow(data);
            }
        }catch(Exception e){
            System.out.println("proses penampilan data Order gagal "+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        data_order = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        data_order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(data_order);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tampil_menu();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable data_order;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
