/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package order;
import modul.koneksi;
import modul.Modul_menu;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author nurhuda ganteng
 */
public class list_menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form list_menu
     */
    public list_menu() {
        initComponents();
        tampad.addColumn("Kode Menu");
        tampad.addColumn("Nama Menu");
        tampad.addColumn("Harga");
        tampad.addColumn("Status");
        data_menu.setModel(tampad);
    }
    
    private DefaultTableModel tampad = new DefaultTableModel();
    
    public void tampil_menu(){
         Connection konsi = null;
        koneksi db = new koneksi();
        String sql ="";
        try{
            hapusTabel(tampad);
            konsi =db.getKoneksi();
            sql ="select kode, nama, harga, status from menus";
            Statement stmt = konsi.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                String kode = rs.getString(1);
                String nama = rs.getString(2);
                String harga = rs.getString(3);
                String status = rs.getString(4);
//                String email = rs.getString(6);
                
                Object[] data ={kode,nama,harga,status};
                
                tampad.addRow(data);
            }
        }catch(Exception e){
            System.out.println("proses penampilan data Menu gagal "+e.getMessage());
        }
    }
    
    public void pilihMenu(){
        int a = data_menu.getSelectedRow();
       if(a == -1){
           JOptionPane.showMessageDialog(null, "Belum ada Menu yang anda Pilih");
       }
       
       String kodeMenu = (String)tampad.getValueAt(a, 0);
      }
    
    public void hapusTabel(DefaultTableModel contoh){
        int a = contoh.getRowCount();
        for(int i = 0; i < a; i++){
            contoh.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        data_menu = new javax.swing.JTable();

        data_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(data_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable data_menu;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
